service: github-webhook-listener

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: ${env:SERVERLESS_STAGE, 'dev'}
  # optional, in MB, default is 1024
  memorySize: 128
  # optional, in seconds, default is 6
  timeout: 3
  # optional, default is true
  versionFunctions: false

  environment:
    GITHUB_WEBHOOK_SECRET: ${env:GITHUB_WEBHOOK_SECRET}
    TRELLO_TOKEN: ${env:TRELLO_TOKEN}
    TRELLO_KEY: ${env:TRELLO_KEY}
    TRELLO_BOARD: ${env:TRELLO_BOARD}
    TRELLO_CARD_PREFIX: ${env:TRELLO_CARD_PREFIX}

functions:
  githubWebhookListener:
    handler: handler.githubWebhookListener
    events:
      - http:
          path: webhook
          method: post
          cors: true
